//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAEmailReminder
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_Main
    {
        public TD_Main()
        {
            this.TD_Transaction = new HashSet<TD_Transaction>();
        }
    
        public int id { get; set; }
        public string control_no { get; set; }
        public System.DateTime issue_dt { get; set; }
        public string issue_by { get; set; }
        public string title { get; set; }
        public string item_code { get; set; }
        public string customer { get; set; }
        public string material { get; set; }
        public string batch_no { get; set; }
        public string job_no { get; set; }
        public string defective_qty { get; set; }
        public string reason { get; set; }
        public System.DateTime expect_date { get; set; }
        public byte Sys_Plant_id { get; set; }
        public System.DateTime effective_dt { get; set; }
        public string preventive { get; set; }
    
        public virtual ICollection<TD_Transaction> TD_Transaction { get; set; }
    }
}
