//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCR_GroupType
    {
        public PCR_GroupType()
        {
            this.PCR_Consider_Master = new HashSet<PCR_Consider_Master>();
            this.PCR_SubGroup = new HashSet<PCR_SubGroup>();
        }
    
        public int group_type_id { get; set; }
        public string group_type { get; set; }
    
        public virtual ICollection<PCR_Consider_Master> PCR_Consider_Master { get; set; }
        public virtual ICollection<PCR_SubGroup> PCR_SubGroup { get; set; }
    }
}
