//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCR_OperateUser
    {
        public string emp_code { get; set; }
        public int pcr_group_id { get; set; }
        public Nullable<int> utype_id { get; set; }
        public Nullable<int> dept_id { get; set; }
    }
}
