//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCR_Impact
    {
        public PCR_Impact()
        {
            this.PCR_SubGroup = new HashSet<PCR_SubGroup>();
        }
    
        public byte imp_id { get; set; }
        public string imp_name { get; set; }
    
        public virtual ICollection<PCR_SubGroup> PCR_SubGroup { get; set; }
    }
}
