//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCR_SubGroup
    {
        public int pcr_group_id { get; set; }
        public string pcr_group_name { get; set; }
        public int group_type_id { get; set; }
        public byte imp_id { get; set; }
    
        public virtual PCR_GroupType PCR_GroupType { get; set; }
        public virtual PCR_Impact PCR_Impact { get; set; }
    }
}
