//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PCREntities : DbContext
    {
        public PCREntities()
            : base("name=PCREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PCR_Consider_Master> PCR_Consider_Master { get; set; }
        public DbSet<PCR_GCode> PCR_GCode { get; set; }
        public DbSet<PCR_GroupType> PCR_GroupType { get; set; }
        public DbSet<PCR_Impact> PCR_Impact { get; set; }
        public DbSet<PCR_OperateUser> PCR_OperateUser { get; set; }
        public DbSet<PCR_SubGroup> PCR_SubGroup { get; set; }
    }
}
