//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SAEntities : DbContext
    {
        public SAEntities()
            : base("name=SAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TD_CarPar> TD_CarPar { get; set; }
        public DbSet<TD_ConcernEN> TD_ConcernEN { get; set; }
        public DbSet<TD_ConcernOther> TD_ConcernOther { get; set; }
        public DbSet<TD_ConcernQC> TD_ConcernQC { get; set; }
        public DbSet<TD_Disposition> TD_Disposition { get; set; }
        public DbSet<TD_File> TD_File { get; set; }
        public DbSet<TD_Main> TD_Main { get; set; }
        public DbSet<TD_Problem> TD_Problem { get; set; }
        public DbSet<TD_Tell> TD_Tell { get; set; }
        public DbSet<TD_Transaction> TD_Transaction { get; set; }
        public DbSet<TD_Transaction_Log> TD_Transaction_Log { get; set; }
        public DbSet<TM_Action> TM_Action { get; set; }
        public DbSet<TM_ActionMapping> TM_ActionMapping { get; set; }
        public DbSet<TM_Admin> TM_Admin { get; set; }
        public DbSet<TM_Disposition> TM_Disposition { get; set; }
        public DbSet<TM_Level> TM_Level { get; set; }
        public DbSet<TM_Problem> TM_Problem { get; set; }
        public DbSet<TM_Status> TM_Status { get; set; }
        public DbSet<TM_SysGroup> TM_SysGroup { get; set; }
        public DbSet<TM_SysGroupCode> TM_SysGroupCode { get; set; }
        public DbSet<TM_SysGroupType> TM_SysGroupType { get; set; }
        public DbSet<TM_SysPlant> TM_SysPlant { get; set; }
        public DbSet<TM_SysUser> TM_SysUser { get; set; }
        public DbSet<TD_SA> TD_SA { get; set; }
        public DbSet<TM_Result> TM_Result { get; set; }
        public DbSet<TD_Inform> TD_Inform { get; set; }
    }
}
