//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_File
    {
        public int file_id { get; set; }
        public Nullable<int> id { get; set; }
        public string file_path { get; set; }
        public Nullable<System.DateTime> upload_dt { get; set; }
        public string upload_by { get; set; }
    
        public virtual TD_Main TD_Main { get; set; }
    }
}
