//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_Main
    {
        public TD_Main()
        {
            this.TD_ConcernEN = new HashSet<TD_ConcernEN>();
            this.TD_ConcernOther = new HashSet<TD_ConcernOther>();
            this.TD_ConcernQC = new HashSet<TD_ConcernQC>();
            this.TD_Disposition = new HashSet<TD_Disposition>();
            this.TD_File = new HashSet<TD_File>();
            this.TD_Problem = new HashSet<TD_Problem>();
            this.TD_Tell = new HashSet<TD_Tell>();
            this.TD_Transaction_Log = new HashSet<TD_Transaction_Log>();
            this.TD_Transaction = new HashSet<TD_Transaction>();
            this.TD_SA = new HashSet<TD_SA>();
            this.TD_Inform = new HashSet<TD_Inform>();
        }
    
        public int id { get; set; }
        public string control_no { get; set; }
        public System.DateTime issue_dt { get; set; }
        public string issue_by { get; set; }
        public string title { get; set; }
        public string item_code { get; set; }
        public string customer { get; set; }
        public string material { get; set; }
        public string batch_no { get; set; }
        public string job_no { get; set; }
        public string defective_qty { get; set; }
        public string reason { get; set; }
        public System.DateTime expect_date { get; set; }
        public byte Sys_Plant_id { get; set; }
        public System.DateTime effective_dt { get; set; }
        public string preventive { get; set; }
        public Nullable<bool> critical_problem { get; set; }
    
        public virtual TD_CarPar TD_CarPar { get; set; }
        public virtual ICollection<TD_ConcernEN> TD_ConcernEN { get; set; }
        public virtual ICollection<TD_ConcernOther> TD_ConcernOther { get; set; }
        public virtual ICollection<TD_ConcernQC> TD_ConcernQC { get; set; }
        public virtual ICollection<TD_Disposition> TD_Disposition { get; set; }
        public virtual ICollection<TD_File> TD_File { get; set; }
        public virtual TM_SysPlant TM_SysPlant { get; set; }
        public virtual ICollection<TD_Problem> TD_Problem { get; set; }
        public virtual ICollection<TD_Tell> TD_Tell { get; set; }
        public virtual ICollection<TD_Transaction_Log> TD_Transaction_Log { get; set; }
        public virtual ICollection<TD_Transaction> TD_Transaction { get; set; }
        public virtual ICollection<TD_SA> TD_SA { get; set; }
        public virtual ICollection<TD_Inform> TD_Inform { get; set; }
    }
}
