//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_SA
    {
        public int id { get; set; }
        public int sa_id { get; set; }
        public string sa_no { get; set; }
        public string cust_name { get; set; }
        public byte result { get; set; }
        public System.DateTime issue_date { get; set; }
        public string reason { get; set; }
        public string file_evidence { get; set; }
        public string update_by { get; set; }
    
        public virtual TD_Main TD_Main { get; set; }
        public virtual TM_Result TM_Result { get; set; }
    }
}
