//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_Transaction_Log
    {
        public int id { get; set; }
        public byte status_id { get; set; }
        public byte lv_id { get; set; }
        public int org_id { get; set; }
        public byte Sys_Plant_id { get; set; }
        public byte rev { get; set; }
        public Nullable<byte> act_id { get; set; }
        public string actor { get; set; }
        public Nullable<System.DateTime> act_dt { get; set; }
        public string comment { get; set; }
    
        public virtual TD_Main TD_Main { get; set; }
        public virtual TM_Action TM_Action { get; set; }
        public virtual TM_Level TM_Level { get; set; }
        public virtual TM_Status TM_Status { get; set; }
        public virtual TM_SysPlant TM_SysPlant { get; set; }
    }
}
