//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Action
    {
        public TM_Action()
        {
            this.TD_Transaction = new HashSet<TD_Transaction>();
            this.TD_Transaction_Log = new HashSet<TD_Transaction_Log>();
        }
    
        public byte act_id { get; set; }
        public string act_name { get; set; }
    
        public virtual ICollection<TD_Transaction> TD_Transaction { get; set; }
        public virtual ICollection<TD_Transaction_Log> TD_Transaction_Log { get; set; }
    }
}
