//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_ActionMapping
    {
        public byte status_id { get; set; }
        public byte lv_id { get; set; }
        public string action_list { get; set; }
    
        public virtual TM_Level TM_Level { get; set; }
        public virtual TM_Status TM_Status { get; set; }
    }
}
