//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Disposition
    {
        public TM_Disposition()
        {
            this.TD_Disposition = new HashSet<TD_Disposition>();
        }
    
        public byte dispos_id { get; set; }
        public string dispos_name { get; set; }
        public bool text_flag { get; set; }
    
        public virtual ICollection<TD_Disposition> TD_Disposition { get; set; }
    }
}
