//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Problem
    {
        public TM_Problem()
        {
            this.TD_Problem = new HashSet<TD_Problem>();
        }
    
        public byte prob_id { get; set; }
        public string prob_name { get; set; }
        public bool text_flag { get; set; }
    
        public virtual ICollection<TD_Problem> TD_Problem { get; set; }
    }
}
