//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_SysPlant
    {
        public TM_SysPlant()
        {
            this.TD_Main = new HashSet<TD_Main>();
            this.TD_Transaction = new HashSet<TD_Transaction>();
            this.TD_Transaction_Log = new HashSet<TD_Transaction_Log>();
            this.TM_SysGroup = new HashSet<TM_SysGroup>();
        }
    
        public byte Sys_Plant_id { get; set; }
        public string Sys_Plant_name { get; set; }
        public bool del_flag { get; set; }
        public System.DateTime update_dt { get; set; }
        public string update_by { get; set; }
    
        public virtual ICollection<TD_Main> TD_Main { get; set; }
        public virtual ICollection<TD_Transaction> TD_Transaction { get; set; }
        public virtual ICollection<TD_Transaction_Log> TD_Transaction_Log { get; set; }
        public virtual ICollection<TM_SysGroup> TM_SysGroup { get; set; }
    }
}
