//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_SysUser
    {
        public byte Sys_Plant_id { get; set; }
        public byte Sys_GroupType_id { get; set; }
        public string Sys_User_id { get; set; }
        public byte lv_id { get; set; }
        public bool user_active { get; set; }
    
        public virtual TM_SysGroup TM_SysGroup { get; set; }
    }
}
