//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_SysGroup
    {
        public TM_SysGroup()
        {
            this.TM_SysUser = new HashSet<TM_SysUser>();
        }
    
        public byte Sys_Plant_id { get; set; }
        public byte Sys_GroupType_id { get; set; }
        public int group_id { get; set; }
        public string Sys_Group_name { get; set; }
        public bool del_flag { get; set; }
        public System.DateTime update_dt { get; set; }
        public string update_by { get; set; }
    
        public virtual TM_SysGroupType TM_SysGroupType { get; set; }
        public virtual TM_SysPlant TM_SysPlant { get; set; }
        public virtual ICollection<TM_SysUser> TM_SysUser { get; set; }
    }
}
