//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_SysGroupType
    {
        public TM_SysGroupType()
        {
            this.TM_SysGroup = new HashSet<TM_SysGroup>();
        }
    
        public byte Sys_GroupType_id { get; set; }
        public string Sys_GroupType_name { get; set; }
        public bool del_flag { get; set; }
        public System.DateTime update_dt { get; set; }
        public string update_by { get; set; }
    
        public virtual ICollection<TM_SysGroup> TM_SysGroup { get; set; }
    }
}
