//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_OnProcess
    {
        public int id { get; set; }
        public string control_no { get; set; }
        public string title { get; set; }
        public System.DateTime issue_dt { get; set; }
        public string issue_by { get; set; }
        public string item_code { get; set; }
        public string group_name { get; set; }
        public string emp_fname { get; set; }
        public string emp_lname { get; set; }
        public int org_id { get; set; }
        public byte status_id { get; set; }
    }
}
